services:
  mongo-tests:
    image: mongo:7.0
    container_name: mongo-tests
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=test-db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--quiet" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s